mux.go
mux_test.go
regexp.go
route.go

This PR introduces a new BuildVarsFunc that can be attached to a route. A BuildVarsFunc allows you to intercept and modify the route variable map passed to `.URL` or `.URLPath` or `.URLHost` before generating the URL.
It is useful when you want to be liberal in matching routes but conservative in constructing them. For example, you might want to normalize all blog post URL slugs to be lowercase, but still match uppercase slugs. Without BuildVarsFunc, you would have to ensure that all callers of `.URL{,Path,Host}` lowercased the slug beforehand. With BuildVarsFunc, you can just call `.URL{,Path,Host}` directly without any additional wrapper functions.
BuildVarsFunc is useful in conjunction with PostMatchFunc at https://github.com/gorilla/mux/pull/53.

BuildVarsFunc: modify route variables before building the URL from a route

---

doc.go

This fixes issue where if user has tab width other than 4, some lines will become misaligned. For example, see the package description at https://godoc.org/github.com/gorilla/mux.

Fix up doc formatting, use spaces for alignment (tabs are for indentation only).

---

mux_test.go
regexp.go
route.go

PR adds support for regexp quantifiers for query strings, so that ```Queries("foo", "{v1:[a-z]{3}}")``` will match for ```&foo=bar``` but not for ```&foo=bars```.
The query matcher currently looks for ```foo=[a-z]{3}``` in the entire URL query string (```baz=ding&foo=bars```) and returns a match. PR looks for ```^foo=[a-z]{3}$``` in only ```foo=bars``` and therefore will not match.

Fixing query regexp patterns with quantifiers 

---

mux_test.go
regexp.go

This PR is a solution to the issue raised by @epelc in https://github.com/gorilla/mux/commit/0c9d5c08c1d6103f2ced11750a195fc94902d3fc#commitcomment-12196652
Not sure if it's the right approach but at least something for discussion. There should be a more idiomatic/explicit way to test if the ```defaultPattern``` should be added to the ```pattern``` but this was an easy way to do it.

fix for empty query

---

mux_test.go
regexp.go

Fix for https://github.com/gorilla/mux/issues/109.
Unfortunately we broke the query matcher when the query's ```defaultPattern``` was changed in https://github.com/gorilla/mux/pull/108.
In this PR the ```getUrlQuery``` method loops over query parameters and only returns a string to match if the the parameter exists in the request (which is how it should have been in the first place).

Issue #109

---

mux.go

For a middleware I'm working on I wanted to use ``CurrentRoute`` and was surprised it always returned ``nil``. Then I realised it is only set just before the handler will be called and will be cleared directly after (on purpose) here: https://github.com/gorilla/mux/blob/master/mux.go#L98
I think it would be a good idea to add a small note, to take the expectation away that ``CurrentRoute`` can be used outside the handler.

Add note about the availability of CurrentRoute.

---

mux_test.go
regexp.go

The router now associates a regexp named group with each mux variable.
It only fills variables when capturing group name match instead of
relying on indices, which doesn't work if a variable regexp has interior
capturing groups.
Fixes #62

fix use of capturing subexpressions in pattern matches.

---

README.md

Added a (small) complete example to the README that includes how to pass a router to `http.ListenAndServe` for newbie Gophers.
Addresses https://github.com/gorilla/mux/issues/32

Updated README w/ runnable example. Addresses #32.

---

mux_test.go

% go vet
mux_test.go:1080: arg len(ancestors) for printf verb %s of wrong type:
int

Correct a printf verb type

---

mux.go
mux_test.go

Issue #20 | `Router.NotFoundHandler` is not used when the router is a subrouter
:-------|:-------
Solution | Move "Not found" logic into `Match` function.
Status | Awaiting Reviewers
This small code move should allow the "deepest" sub-router to respond with it's `NotFoundHandler`, thanks to the recursive nature of `Match`.  As this is my first pull to this repository, I expect there to be more steps to make this change than the code fix alone.  If a repository administrator leaves a comment on what else is necessary to merge to the repository, I will be happy to comply.

`Router.NotFoundHandler` is not used when the router is a subrouter

---

bench_test.go
regexp.go

This is an alternative way to fix #62 . Current fix uses named groups and access matches via SubexpNames. Alternative is to wrap regexp expressions in normal groups iff whole expression is not already in a group. To access only mux provided group matches it is enough to use non overlapping ranges from FindStringSubmatchIndex. Adding 2 benchamrks shows runtime speedup and decreased allocations:
```
benchmark                             old ns/op     new ns/op     delta
BenchmarkMux-4                        4916          4179          -14.99%
BenchmarkMuxAlternativeInRegexp-4     7817          6198          -20.71%
BenchmarkManyPathVariables-4          9885          8625          -12.75%
benchmark                             old allocs     new allocs     delta
BenchmarkMux-4 …
```

Alternative fix for #62 with speedup

---

mux_test.go
regexp.go

Changes in https://github.com/gorilla/mux/pull/144 broke regexp matching for case insensitive groups. 
This adds a test scenario and a small hunk of code reverted to what it was prior to the PR.

Allowing case insensitive regexp groups after PR #144

---

old_test.go

const DefaultRemoteAddr is unused in old_test.

old_test: const DefaultRemoteAddr is unused.

---

README.md

As someone new to Go and still learning Go idioms, I spent a little bit too long diagnose why
the `ListenAndServe` call wasn't blocking. The reason is returned as an error but the full example in the README does not log the return value. My reason was port 8000 was occupied on my machine.
The examples [here](https://golang.org/pkg/net/http/) wrap `ListenAndServe` in `log.Fatal` so I'm guessing this is an idiom.
Might save someone a few mins of scratching their head, particularly if they're new to Go, like me.

Log ListenAndServe's err response in Full Example

---

mux.go
mux_test.go

In old version error was not returned properly, In one walkFn call
error was checked only for SkipRouter but not for nil.

Fix error handling in  Router.Walk

---

README.md
doc.go

Addresses the static file serving docs in https://github.com/gorilla/mux/issues/151

[docs] Add static file example to README; doc.go.

---

mux.go
mux_test.go

This PR fixes a panic introduces by PR https://github.com/gorilla/mux/pull/184 that manifests within Google App Engine. For more information about the underlying problem, see issue https://github.com/gorilla/mux/issues/188.
Basically, certain assumptions about the value of `RequestURI` don't hold within the App Engine sandbox environment.

Make the new getPath method safer, fixing panics within App Engine

---

mux_test.go
regexp.go

The current implementation was failing in a case where there are two route vars right next to each other and the second one matched the empty string. Because of that, `prevEnd < matches[i+1]` evaluated to `false` and the matches got assigned to the wrong names.
Having a capturing regexp group in a route pattern is never useful. This commit changes the tests accordingly. Another option would be to automatically turn capturing groups into non-capturing ones (adding the `?:` automatically).

Simplify extractVars, fixes edge cases.

---

mux_test.go
route.go

This should fix https://github.com/gorilla/mux/issues/79. 
Looking for feedback!

Adding in a check for routes with just /

---

README.md

(this confused the heck out of me while trying to use Gorilla)
- Changed `request` to be just `r`, like the other handlers.
- Created complete wrapper function instead of just 2 lines.

Clarify how route variables work. (#151)

---

bench_test.go

Fixing Regexp in the benchmark test

Fixing small bug in the benchmark test

---

README.md
mux_test.go
route.go

Add method `GetPathRegexp`  which returns original regex for path.
Add method `GetMethods` which returns all available methods for path.

Get extra information about a route for a documentation 

---

mux_test.go
route.go

- Capture first scheme configured for a route for use when building URLs.
- Add new Route.URLScheme method similar to URLHost and URLPath.
- Update Route.URLHost and Route.URL to use the captured scheme if present.
Fixes #13. Supersedes #161.

Support building URLs with non-http schemes.

---

mux.go
mux_test.go

Matches all routes instead of just routes with paths.
Fixes #261

Update Walk to match all subrouters

---

README.md

Looks like there was just part of a conflict marker in the README file, so I figured I'd remove it.

Removing half of conflict marker

---

README.md

In the "Listing Routes" example code, `.HandleFunc` was being called on a `*mux.Route` rather than `*mux.Router`. Updated the example code to work.

Fix invalid example code

---

README.md
doc.go
mux_test.go
regexp.go
route.go

This PR builds on and supersedes #230. It fixes #238 and #255.
* Rebased the two commits by @pamburus from #230 and resolved the conflicts.
* Updated README.md and the godocs to reflect the new functionality.
* Added a test for escaped query values, which duplicated #238.
* Added a fix for #238. The fix for that—changing the default pattern for query values from `[^?&]*` to `.*`—is safe because the Go standard library has already removed the semantically important `?` and `&` characters from the query string when parsing it into individual key/value pairs. The matching logic in `routeRegexp.matchQueryString` uses the regex to match already parsed and decoded query values returned by `routeRegexp.getURLQuery`.

Add support for queries in URL reversing.

---

mux.go
mux_test.go
old_test.go
route.go

This is my attempt to handle the Issue #271 . All existing tests are passing and I have added an additional test for current feature. 
This is my first major contribution to a big open source project. Please feel free to suggest any change.

Fix #271:  Returning 405 instead of 404 when request has method mismatch with route

---

mux_test.go

WriteHeader did only set status field for a local copy that was discarded
upon return.

Fix WriteHeader in TestA301ResponseWriter.

---

mux.go
regexp.go

This change drops support of go < 1.5. go1.4 has been [officially unsupported](https://golang.org/doc/devel/release.html#policy) since go1.6 was released 2016/02/17.
The PR was motivated by a bug I discovered, where `req.RequestURI` was returning `""`, so my router was failing to route on the escaped path.
Very open to thoughts and/feedback on how to proceed. Thanks!

Use req.URL.EscapedPath() instead of getPath(req)

---

mux.go

The return values are getting confusing. Hopefully this helps.

Document router.Match

---

mux.go
mux_test.go
route.go

As discussed in #293, it should be useful if `RouteMatch.MatchErr` were set to an error if no match is found, even if some subrouters have a custom `NotFoundHandler`.

MatchErr is set to ErrNotFound if NotFoundHandler is used

---

mux.go

https://github.com/gorilla/mux/pull/306 changed UseEncodedPath to use native go encoded path handling so cautions in it's docs are no longer applicable.

docs) fix outdated UseEncodedPath method docs

---

mux_test.go
route.go

Fix handler match for subrouters created from method-matcher-based routes where the paths match (issue #300).
- Add a test case for routers with methods-based subrouters and matching paths
- Pass the test case with an addition to `Route.Match`

[bugfix] Fix method subrouter handler matching (#300)

---

mux.go

* StrictSlash enabled routes return a 301 to the client
* As per the HTTP standards, non-idempotent methods, such as POST or PUT, will be followed with a GET by the client
* Users should use middleware if they wish to change this behaviour to return a HTTP 308.
Addresses https://github.com/gorilla/mux/issues/308

[docs] Note StrictSlash re-direct behaviour #308

---

example_route_test.go
route.go

Implements the documentation aspect of #124.
Updates the documentation comment header for `route.go:Route.HeadersRegexp`. And also adds `example_route_test.go` containing:  
1. `ExampleRoute_HeadersRegexp`. Demonstrates the wildcard behavior of Go's `regexp.Compile`.
2. `ExampleRoute_HeadersRegexp_exactMatch`. Demonstrates strict matching using start and end of string anchors.

[docs] Add example usage for Route.HeadersRegexp

---

test_helpers.go
testing.go

As discussed in #233, it will be useful to have a test focused API to set URL params. Currently this is not possible because the route key type used to store the vars in the context is private and the setVars function is also private.
Currently there are two work arounds to address this, the first being to make pull the vars extraction up in to the middleware layer, which requires a significant refactor and the other is to spin up a server and running the request through a route to populate the context with the vars. The problem with this is that it's very heavy handed and for those running tests in hosted CI environments like travis, the extra bloat can slow down test execution potentially to the point where testing handlers no longer becomes viable.
This should allow for the testing of …

Public test API to set URL params

---

mux_test.go
old_test.go
regexp.go
route.go

The existing options matchPrefix, matchHost, and matchQueries are
mutually exclusive so there's no point in having a separate boolean
argument for each one. It's clearer if there's a single type variable.
strictSlash and useEncodedPath were also being passed as naked bools so
I've wrapped these in a struct called routeRegexpOptions for more clarity
at the call site.

refactor routeRegexp, particularily newRouteRegexp.

---

README.md
doc.go
middleware.go
middleware_test.go
mux.go

See discussion in #293 for more details.

Add middleware support as discussed in #293

---

route.go

They actually return an error instead of an empty list. `GetMethods` happened to not return an error, but it should for consistency, so I added that as well.

Document route.Get* methods consistently

---

mux_test.go
test_helpers.go

Clarify in documentation that SetURLVars does not modify the given *htttp.Request, provide an example of usage.
Addresses #334

[docs] Clarify SetURLVars

---

doc.go
example_authentication_middleware_test.go

Go provides HTTP status codes as  const variables.

Modify 403 status code to const variable

---

README.md
doc.go
example_authentication_middleware_test.go

I missed README file.
[related](https://github.com/gorilla/mux/pull/349)

Modify http status code to variable in README

---

middleware.go

Enables neater syntax when chaining several middleware functions:
``` go
router.Use(mwFunc1, mwFunc2, mwfunc3)
```
Fully backwards-compatible when using a single function as argument.

Make Use() variadic

---

README.md

The example in the README does not pass the request through a mux therefore the request variables from the path are never populated. Update the sample to create a minimum viable router to use.
Fixes #373

Doc fix for testing variables in path

---

.travis.yml

Only run vet on the latest Go version.

Always run on the latest stable Go version.

---

regexp.go

Go provides HTTP status codes as constants

Use constant for 301 status code in regexp.go

---

mux.go
mux_test.go
regexp.go
route.go

In #389, @fstanis highlighted an issue with routes branched off a subrouter not filtering by `Methods()` as intended; they wrote demonstrative tests in #390. 
I identified several more matchers which suffered the same problem. Specifically, if you invoke `Schemes()`, `Headers()`, ~or `Query()`~ **(edit: this is incorrect)** before invoking `Subrouter()`, your config is discarded for child routes. I have incorporated @fstanis' tests for `Methods()` and added a few more for the other three methods; all of the negative cases (`shouldMatch: false`) would currently fail on master. 
As far as I can tell, passing on these matchers isn't addressed in the code because I don't think this is necessarily the most likely use case for `Subrouter` (I imagine it was written to effectively avoid typing …

Subroute configuration fixes

---

README.md

Because domain.com is an actual business, example.com should be used for example purposes.

Replace domain.com with example.com

---

middleware_test.go
route.go

fix for issue #429

---

mux_test.go
regexp.go

I ran into #2, i think its safe to simply `return r.Host` because `r.URL.IsAbs()` case is already doing that and is covered by existing tests cases.

fix #2, return full host:port info from getHost

---

README.md

From the docs: Changing the header map after a call to WriteHeader (or
Write) has no effect unless the modified headers are
trailers.

Call WriteHeader after setting other header(s) in the example

---

.travis.yml

`go vet` instead of `go tool vet`

fix go1.12 go vet usage

---

.circleci/config.yml
README.md

[WIP] Create CircleCI config

---

middleware_test.go

Part of #409, awaiting feedback on whether I should update `old_test.go` before tagging that this completely closes that issue.
Uses Go subtests for all the middleware tests. I don't love the solution for `CORSMethodMiddleware`, because those tests don't really make sense, because that middleware doesn't really make sense (my bad, see #476). The new tests I wrote in #477 use subtests and completely replace the current tests for that, though.

Use subtests for middleware tests

---

README.md
go.mod

Fixes #464
1. Adds documentation to the README.md for using mux to serve API endpoints alongside a SPA.
**Testing**
I ran create-react-app, made a prod build, copied the build directory, and tested this out. Seems to work great.

Add documentation for using mux to serve a SPA

---

mux_test.go
route.go

Fixes #509
1. check new handler not nil before discarding MethodNotAllowed error
2. add unit test

bugfix/subrouter custom methodNotAllowed handler returning 404 (#509)

---

mux_httpserver_test.go
mux_test.go
old_test.go
route.go

It's not expected that the request's URL is fully populated when used on
the server-side (it's more of a client-side field), so we shouldn't
expect it to be present.
In practice, it's only rarely set at all on the server, making mux's
`Schemes` matcher tricky to use as it is.
This commit adds a test which would have failed before demonstrating the
problem, as well as a fix which I think makes `.Schemes` match what
users expect.
This will technically break anyone who did the following:
```go
router.Schemes("") // match http and https
```

Guess the scheme if r.URL.Scheme is unset

---

middleware.go
middleware_test.go

Fixes #534 
1. Adds a test case for the repro given in issue #534
2. Fixes the logic in CORSMethodMiddleware to handle matching routes better (now more closely mirrors the way routes are actually matched, just ignoring method mismatch errors)

Fix the CORSMethodMiddleware bug with subrouters

---

regexp.go

Fixed:
1. mux.go:366:5: error var SkipRouter should have name of the form ErrFoo
2. regexp.go:184:9: if block ends with a return statement, so drop this else and outdent its block

Fixed golint warnings

---

regexp.go
regexp_test.go

A production server is seeing a significant amount of allocations in (*routeRegexp).getURLQuery
Since it is only interested in a single value and only the first value we create a specialized function for that.
Comparing a few parameter parsing scenarios:
```
Benchmark_findQueryKey/0-8 	 7184014	       168 ns/op	       0 B/op	       0 allocs/op
Benchmark_findQueryKey/1-8 	 5307873	       227 ns/op	      48 B/op	       3 allocs/op
Benchmark_findQueryKey/2-8 	 1560836	       770 ns/op	     483 B/op	      10 allocs/op
Benchmark_findQueryKey/3-8 	 1296200	       931 ns/op	     559 B/op	      11 allocs/op
Benchmark_findQueryKey/4-8 	  666502	      1769 ns/op	       3 B/op	       1 allocs/op
Benchmark_findQueryKeyGoLib/0-8 	 1740973	       690 ns/op	     864 B/op	       8 …
```

Reduce allocations in (*routeRegexp).getURLQuery

---

mux.go

Fixes #
Comment for CurrentRoute claimed that setting the KeepContext option would propagate
the Route even after the request. The KeepContext option is deprecated and has no effect.
> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!

Remove stale text from comment.

---

old_test.go
regexp.go

Continuing from PR #447 we have to add extra
check to ignore the port as well

fix: regression in vars extract for wildcard host

---

mux.go

I was searching for 404 in the docs and didn't find anything and almost assumed Mux didn't have the ability for a custom 404 handlers. Add another sentence with "404" and "Not Found" so quick searching can find them.
Same for 405.

Include "404" and "405" in the docs

---

README.md
regexp.go

Replaced hardcoded constant `regexType*` declarations with `iota`.

regexp: use iota instead of hardcoded values for regexType*

---

README.md

Fixes #692 
1. Fix the `README.md` middleware section. An example is demonstrated about the `authenticationMiddleware` and `authenticationMiddleware` initialization is incorrect because incorrect initialization in real-world code throws a panic runtime error.  The correct way of initialization is 
```golang
amw := authenticationMiddleware{make(map[string]string)}
```
and this PR fixes that. No test cases are required in this case because in the example file it is already written correctly 
https://github.com/gorilla/mux/blob/master/example_authentication_middleware_test.go#L43
> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!

Fix `authenticationMiddleware` initialization in the `README.md` file

---

doc.go
mux.go

`go fmt` now formats godoc comments. I apply it.
- Closes #

run go fmt with Go 1.20

---

mux.go

This brings these docs in line with the rest of the repository.
Remove use of hyphen in "redirect" in the documentation.
`make verify` is not passing for me locally, but the failures are in unrelated
files. It may be because I don't see a .golangci.yml in the repo. I assume it's
using my linting config instead.

Use "redirect" rather than "re-direct" in docs

---

mux_test.go
route.go

Fix made in #712 is not an optimal solution to the problem #704, since it completely prevents the possibility of getting error `ErrMethodMismatch` for subrouters.
The proposed solution corrects this situation and allows correct error handling of invalid query paramaters and preserves the possibility of getting `ErrMethodMismatch` in subrouters.
- Related Issue #739
- Closes #739

[BUG #739] Fixed handling of invalid query params

---

mux.go
regexp.go
route_test.go

Route creation is slow as it always invokes regexp.Compile, increasing memory and cpu pressure in cases where route creation is common (e.g. an api gateway reloading changes). This PR adds a exported `RegexpCompileFunc` variable, that's possible to override with other implementations, adding caches. Added a benchmark.
```
goos: linux
goarch: amd64
pkg: github.com/gorilla/mux
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkNewRouter-8             	   36786	     34450 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8             	   44839	     31840 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8             	   48939	     23419 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8             	   52255	     25949 ns/op	   26327 B/op	     374 …
```

Add RegexpCompileFunc to override regexp.Compile

---

mux.go

chore: fix function name in comment

---

middleware.go
middleware_test.go
route.go

Added support for route specific middleware using the `.Use` method.
Using the `.Use` method on `Route` middlewares can be set on a specific route.
Example:
```go
router.HandleFunc("/", handlerFunc).Use(middleware)
```
- Closes #

Feature route middleware with `.Use`

---

mux.go
route.go
route_test.go

Added metadata to route. as proposed in #750 
Documentation will be added uppon request.
- Related Issue #750 
- Closes #750 

Feature route metadata

---

mux.go
mux_test.go

Named routes are great, and being able to retrieve the URL for a route based on its name is a feature I use a lot. However, when handlers reside in a different package from the router instance, this can become cumbersome. Therefore, it would be great if we could fetch the current router just like we can fetch the current route. This PR adds that functionality.
```go
router := mux.CurrentRouter(r)
```
By default, the router is added to the request context but can be omitted using the `omitRouterFromContext` option or by calling `router.OmitRouterFromContext(true)`.
- Closes #

Feature router in request context
