mux_test.go

Add tests for patterns with pipe

---

mux_test.go

Sorry, I realized the previous test doesn't make sense if we don't test the other pipe possibility...
refs #62

Add complementary test for patterns with pipe

---

doc.go
mux.go
mux_test.go
route.go

Address #16  and added the support for regular expressions.

Issue #16: Added regex support for matching headers

---

README.md

Fixed GoDoc badge.

---

route.go

Legacy commits were made in previous PR. Fixed the documentation in mini commit.

Fixed documentation from Issue 16

---

mux.go

Fix a typo in the comment docs, add a few more.

Typo and Docs

---

.travis.yml

This change augments the Travis CI build to perform:
- Check that all files follow gofmt style, including -s (simplify) option.
- Check that go vet does not report any problems.
- Use race detector when running tests, to ensure there are no data races found.
Doing this will help catch issues like in #133 at the time the change is made, automatically.

Travis: Perform gofmt, go vet checks; use race detector during tests.

---

doc.go
mux.go
old_test.go
regexp.go
route.go

- SkipRouter should also be ErrRouterSkipped (or similar) but a change would
break the public API.

[docs] Satisfied golint.

---

.travis.yml
mux.go
mux_test.go
route.go

This PR rebases https://github.com/gorilla/mux/pull/54 on the latest master. Most works were done by @whatupdave.
/cc @elithrar

Add SkipClean option

---

.travis.yml

Ref https://github.com/gorilla/mux/commit/12a13f34e4fd6f7c8cbd499c446bded8d09ad8ad#commitcomment-17371551

[ci] Update .travis-ci to skip install block.

---

mux.go
mux_test.go
old_test.go
regexp.go
route.go

Add useEncodedPath option to router and routes

---

README.md

Add sourcegraph badge

---

route.go

Fixed the unclear logic that was discussed in https://github.com/gorilla/mux/pull/215 comment:
https://github.com/gorilla/mux/pull/215#issuecomment-282473563
I'm not sure if extra tests are needed here, but if they are let me know so I can add them.

updating logic in route matcher, cleaner and saner

---

README.md
mux.go
mux_test.go

Update ancestors parameter for WalkFunc for matcher subrouters

---

mux.go
mux_test.go
route.go

Use scheme from parent router when building URLs.

---

.travis.yml

Allow CI failures on tip (warn, don't error)

[build] Allow tip failures

---

README.md

* Added a graceful shutdown example (was writing this for a project and figured I'd share)
* Fix indentation across the README.

[docs] Add graceful shutdown example

---

README.md

Just making the graceful shutdown example copy paste-able

Make shutdown docs compilable

---

README.md

Addresses a checkbox in https://github.com/gorilla/mux/issues/151

[docs] Add testing example

---

doc.go

Addresses https://github.com/gorilla/mux/pull/294#discussion_r162309666

[docs] Fix doc.go

---

README.md

README.md file , Graceful Shutdown demo code miss "time" package import
https://github.com/gorilla/mux/blob/master/README.md#graceful-shutdown

README.md: add miss "time"

---

README.md

Fixes #323.
Also removed the duplicate "listing routes" example.

README.md: Improve "walking routes" example.

---

AUTHORS
LICENSE

If this looks good, I'll replicate across the other repos.
- I've kept the list of authors minimal - not to diminish the contributions of others, but because it's easier for contributors to add their names (if they so wish).
- The list is sorted.

Update LICENSE & AUTHORS files.

---

mux_test.go

Use subtests in mux_test.go

---

context.go
mux.go

remove redundant code that remove support gorilla/context

---

route.go

Minor spelling mistake 

---

doc.go

Closes #488 
Runnable example of issue: https://play.golang.org/p/a45X5e78c0h
Runnable example with fix: https://play.golang.org/p/zE7dBKdOjCF

Fix nil panic in authentication middleware example

---

mux_test.go

Avoid unnecessary conversion

---

mux.go

Use a single append call instead of a ranged for loop.

Simplify code

---

README.md

(Self hosting the gorilla image for testing)

Update README (self-host logo)

---

regexp.go
route.go

Simple optimisation to reduce memory allocations and copying(while appending).

Added capacity to slice creation, when capacity is known

---

mux_test.go

fix headers regexp test case

---

README.md

- Related Issue #710
- Closes #710

Updated the logo in README.md

---

README.md

Changed the SPA handler example in README.md in two areas. First, made sure to actually include the requested path in the call to `filepath.Join`. Secondly, if the requested path hits a directory, I think it would be beneficial to also serve the `indexPath` file, and not list the directory contents. I also edited the comments in the `README.md` file accordingly.
- Closes #

fix SPA handler in README.md
